//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenERP.Web.WCF.Payment {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessLogicFault", Namespace="http://idu0080.ttu.ee")]
    [System.SerializableAttribute()]
    public partial class BusinessLogicFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF.Payment.IPayment")]
    public interface IPayment {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/Add", ReplyAction="http://tempuri.org/IPayment/AddResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OpenERP.Web.WCF.Payment.BusinessLogicFault), Action="http://tempuri.org/IPayment/AddBusinessLogicFaultFault", Name="BusinessLogicFault", Namespace="http://idu0080.ttu.ee")]
        int Add(int invoiceId, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/Add", ReplyAction="http://tempuri.org/IPayment/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(int invoiceId, double amount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPaymentChannel : OpenERP.Web.WCF.Payment.IPayment, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentClient : System.ServiceModel.ClientBase<OpenERP.Web.WCF.Payment.IPayment>, OpenERP.Web.WCF.Payment.IPayment {
        
        public PaymentClient() {
        }
        
        public PaymentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(int invoiceId, double amount) {
            return base.Channel.Add(invoiceId, amount);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int invoiceId, double amount) {
            return base.Channel.AddAsync(invoiceId, amount);
        }
    }
}
