//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenERP.Web.WCF.Invoice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OpenErpEntityBase", Namespace="http://schemas.datacontract.org/2004/07/OpenERP.Library")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OpenERP.Web.WCF.Invoice.ProductProduct))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OpenERP.Web.WCF.Invoice.AccountInvoice))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OpenERP.Web.WCF.Invoice.AccountInvoiceLine))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OpenERP.Web.WCF.Invoice.ResPartner))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OpenERP.Web.WCF.Invoice.Customer))]
    public partial class OpenErpEntityBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductProduct", Namespace="http://schemas.datacontract.org/2004/07/OpenERP.Library")]
    [System.SerializableAttribute()]
    public partial class ProductProduct : OpenERP.Web.WCF.Invoice.OpenErpEntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DefaultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ean13Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HrExpenseOkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> IncomingQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> LstPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameTemplateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> OutgoingQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartnerRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PriceExtraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PriceMarginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PricelistIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductTmplIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProjectIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> QtyAvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TrackIncomingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TrackOutgoingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TrackProductionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValuationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VariantsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> VirtualAvailableField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultCode {
            get {
                return this.DefaultCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultCodeField, value) != true)) {
                    this.DefaultCodeField = value;
                    this.RaisePropertyChanged("DefaultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ean13 {
            get {
                return this.Ean13Field;
            }
            set {
                if ((object.ReferenceEquals(this.Ean13Field, value) != true)) {
                    this.Ean13Field = value;
                    this.RaisePropertyChanged("Ean13");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HrExpenseOk {
            get {
                return this.HrExpenseOkField;
            }
            set {
                if ((this.HrExpenseOkField.Equals(value) != true)) {
                    this.HrExpenseOkField = value;
                    this.RaisePropertyChanged("HrExpenseOk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> IncomingQty {
            get {
                return this.IncomingQtyField;
            }
            set {
                if ((this.IncomingQtyField.Equals(value) != true)) {
                    this.IncomingQtyField = value;
                    this.RaisePropertyChanged("IncomingQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LocationId {
            get {
                return this.LocationIdField;
            }
            set {
                if ((this.LocationIdField.Equals(value) != true)) {
                    this.LocationIdField = value;
                    this.RaisePropertyChanged("LocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> LstPrice {
            get {
                return this.LstPriceField;
            }
            set {
                if ((this.LstPriceField.Equals(value) != true)) {
                    this.LstPriceField = value;
                    this.RaisePropertyChanged("LstPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameTemplate {
            get {
                return this.NameTemplateField;
            }
            set {
                if ((object.ReferenceEquals(this.NameTemplateField, value) != true)) {
                    this.NameTemplateField = value;
                    this.RaisePropertyChanged("NameTemplate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> OutgoingQty {
            get {
                return this.OutgoingQtyField;
            }
            set {
                if ((this.OutgoingQtyField.Equals(value) != true)) {
                    this.OutgoingQtyField = value;
                    this.RaisePropertyChanged("OutgoingQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartnerRef {
            get {
                return this.PartnerRefField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerRefField, value) != true)) {
                    this.PartnerRefField = value;
                    this.RaisePropertyChanged("PartnerRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> PriceExtra {
            get {
                return this.PriceExtraField;
            }
            set {
                if ((this.PriceExtraField.Equals(value) != true)) {
                    this.PriceExtraField = value;
                    this.RaisePropertyChanged("PriceExtra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> PriceMargin {
            get {
                return this.PriceMarginField;
            }
            set {
                if ((this.PriceMarginField.Equals(value) != true)) {
                    this.PriceMarginField = value;
                    this.RaisePropertyChanged("PriceMargin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PricelistId {
            get {
                return this.PricelistIdField;
            }
            set {
                if ((this.PricelistIdField.Equals(value) != true)) {
                    this.PricelistIdField = value;
                    this.RaisePropertyChanged("PricelistId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductTmplId {
            get {
                return this.ProductTmplIdField;
            }
            set {
                if ((this.ProductTmplIdField.Equals(value) != true)) {
                    this.ProductTmplIdField = value;
                    this.RaisePropertyChanged("ProductTmplId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProjectId {
            get {
                return this.ProjectIdField;
            }
            set {
                if ((this.ProjectIdField.Equals(value) != true)) {
                    this.ProjectIdField = value;
                    this.RaisePropertyChanged("ProjectId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> QtyAvailable {
            get {
                return this.QtyAvailableField;
            }
            set {
                if ((this.QtyAvailableField.Equals(value) != true)) {
                    this.QtyAvailableField = value;
                    this.RaisePropertyChanged("QtyAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TrackIncoming {
            get {
                return this.TrackIncomingField;
            }
            set {
                if ((this.TrackIncomingField.Equals(value) != true)) {
                    this.TrackIncomingField = value;
                    this.RaisePropertyChanged("TrackIncoming");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TrackOutgoing {
            get {
                return this.TrackOutgoingField;
            }
            set {
                if ((this.TrackOutgoingField.Equals(value) != true)) {
                    this.TrackOutgoingField = value;
                    this.RaisePropertyChanged("TrackOutgoing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TrackProduction {
            get {
                return this.TrackProductionField;
            }
            set {
                if ((this.TrackProductionField.Equals(value) != true)) {
                    this.TrackProductionField = value;
                    this.RaisePropertyChanged("TrackProduction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valuation {
            get {
                return this.ValuationField;
            }
            set {
                if ((object.ReferenceEquals(this.ValuationField, value) != true)) {
                    this.ValuationField = value;
                    this.RaisePropertyChanged("Valuation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Variants {
            get {
                return this.VariantsField;
            }
            set {
                if ((object.ReferenceEquals(this.VariantsField, value) != true)) {
                    this.VariantsField = value;
                    this.RaisePropertyChanged("Variants");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> VirtualAvailable {
            get {
                return this.VirtualAvailableField;
            }
            set {
                if ((this.VirtualAvailableField.Equals(value) != true)) {
                    this.VirtualAvailableField = value;
                    this.RaisePropertyChanged("VirtualAvailable");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountInvoice", Namespace="http://schemas.datacontract.org/2004/07/OpenERP.Library")]
    [System.SerializableAttribute()]
    public partial class AccountInvoice : OpenERP.Web.WCF.Invoice.OpenErpEntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AddressInvoiceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> AmountTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrencyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateInvoiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OpenERP.Web.WCF.Invoice.AccountInvoiceLine[] InvoiceLinesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JournalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MoveIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PartnerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> ResidualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddressInvoiceId {
            get {
                return this.AddressInvoiceIdField;
            }
            set {
                if ((this.AddressInvoiceIdField.Equals(value) != true)) {
                    this.AddressInvoiceIdField = value;
                    this.RaisePropertyChanged("AddressInvoiceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> AmountTotal {
            get {
                return this.AmountTotalField;
            }
            set {
                if ((this.AmountTotalField.Equals(value) != true)) {
                    this.AmountTotalField = value;
                    this.RaisePropertyChanged("AmountTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyId {
            get {
                return this.CompanyIdField;
            }
            set {
                if ((this.CompanyIdField.Equals(value) != true)) {
                    this.CompanyIdField = value;
                    this.RaisePropertyChanged("CompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrencyId {
            get {
                return this.CurrencyIdField;
            }
            set {
                if ((this.CurrencyIdField.Equals(value) != true)) {
                    this.CurrencyIdField = value;
                    this.RaisePropertyChanged("CurrencyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateInvoice {
            get {
                return this.DateInvoiceField;
            }
            set {
                if ((this.DateInvoiceField.Equals(value) != true)) {
                    this.DateInvoiceField = value;
                    this.RaisePropertyChanged("DateInvoice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OpenERP.Web.WCF.Invoice.AccountInvoiceLine[] InvoiceLines {
            get {
                return this.InvoiceLinesField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceLinesField, value) != true)) {
                    this.InvoiceLinesField = value;
                    this.RaisePropertyChanged("InvoiceLines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JournalId {
            get {
                return this.JournalIdField;
            }
            set {
                if ((this.JournalIdField.Equals(value) != true)) {
                    this.JournalIdField = value;
                    this.RaisePropertyChanged("JournalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MoveId {
            get {
                return this.MoveIdField;
            }
            set {
                if ((this.MoveIdField.Equals(value) != true)) {
                    this.MoveIdField = value;
                    this.RaisePropertyChanged("MoveId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PartnerId {
            get {
                return this.PartnerIdField;
            }
            set {
                if ((this.PartnerIdField.Equals(value) != true)) {
                    this.PartnerIdField = value;
                    this.RaisePropertyChanged("PartnerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceType {
            get {
                return this.ReferenceTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceTypeField, value) != true)) {
                    this.ReferenceTypeField = value;
                    this.RaisePropertyChanged("ReferenceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Residual {
            get {
                return this.ResidualField;
            }
            set {
                if ((this.ResidualField.Equals(value) != true)) {
                    this.ResidualField = value;
                    this.RaisePropertyChanged("Residual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountInvoiceLine", Namespace="http://schemas.datacontract.org/2004/07/OpenERP.Library")]
    [System.SerializableAttribute()]
    public partial class AccountInvoiceLine : OpenERP.Web.WCF.Invoice.OpenErpEntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AccountAnalyticIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> DiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PartnerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PriceSubtotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PriceUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OpenERP.Web.WCF.Invoice.ProductProduct ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UosIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AccountAnalyticId {
            get {
                return this.AccountAnalyticIdField;
            }
            set {
                if ((this.AccountAnalyticIdField.Equals(value) != true)) {
                    this.AccountAnalyticIdField = value;
                    this.RaisePropertyChanged("AccountAnalyticId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CompanyId {
            get {
                return this.CompanyIdField;
            }
            set {
                if ((this.CompanyIdField.Equals(value) != true)) {
                    this.CompanyIdField = value;
                    this.RaisePropertyChanged("CompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Discount {
            get {
                return this.DiscountField;
            }
            set {
                if ((this.DiscountField.Equals(value) != true)) {
                    this.DiscountField = value;
                    this.RaisePropertyChanged("Discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceId {
            get {
                return this.InvoiceIdField;
            }
            set {
                if ((this.InvoiceIdField.Equals(value) != true)) {
                    this.InvoiceIdField = value;
                    this.RaisePropertyChanged("InvoiceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Origin {
            get {
                return this.OriginField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginField, value) != true)) {
                    this.OriginField = value;
                    this.RaisePropertyChanged("Origin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PartnerId {
            get {
                return this.PartnerIdField;
            }
            set {
                if ((this.PartnerIdField.Equals(value) != true)) {
                    this.PartnerIdField = value;
                    this.RaisePropertyChanged("PartnerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> PriceSubtotal {
            get {
                return this.PriceSubtotalField;
            }
            set {
                if ((this.PriceSubtotalField.Equals(value) != true)) {
                    this.PriceSubtotalField = value;
                    this.RaisePropertyChanged("PriceSubtotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> PriceUnit {
            get {
                return this.PriceUnitField;
            }
            set {
                if ((this.PriceUnitField.Equals(value) != true)) {
                    this.PriceUnitField = value;
                    this.RaisePropertyChanged("PriceUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OpenERP.Web.WCF.Invoice.ProductProduct Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UosId {
            get {
                return this.UosIdField;
            }
            set {
                if ((this.UosIdField.Equals(value) != true)) {
                    this.UosIdField = value;
                    this.RaisePropertyChanged("UosId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResPartner", Namespace="http://schemas.datacontract.org/2004/07/OpenERP.Library")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OpenERP.Web.WCF.Invoice.Customer))]
    public partial class ResPartner : OpenERP.Web.WCF.Invoice.OpenErpEntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/OpenERP.Library.Entities")]
    [System.SerializableAttribute()]
    public partial class Customer : OpenERP.Web.WCF.Invoice.ResPartner {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessLogicFault", Namespace="http://idu0080.ttu.ee")]
    [System.SerializableAttribute()]
    public partial class BusinessLogicFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF.Invoice.IInvoice")]
    public interface IInvoice {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/Create", ReplyAction="http://tempuri.org/IInvoice/CreateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OpenERP.Web.WCF.Invoice.BusinessLogicFault), Action="http://tempuri.org/IInvoice/CreateBusinessLogicFaultFault", Name="BusinessLogicFault", Namespace="http://idu0080.ttu.ee")]
        OpenERP.Web.WCF.Invoice.AccountInvoice Create(OpenERP.Web.WCF.Invoice.Customer customer, OpenERP.Web.WCF.Invoice.ProductProduct product, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/Create", ReplyAction="http://tempuri.org/IInvoice/CreateResponse")]
        System.Threading.Tasks.Task<OpenERP.Web.WCF.Invoice.AccountInvoice> CreateAsync(OpenERP.Web.WCF.Invoice.Customer customer, OpenERP.Web.WCF.Invoice.ProductProduct product, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/GetById", ReplyAction="http://tempuri.org/IInvoice/GetByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OpenERP.Web.WCF.Invoice.BusinessLogicFault), Action="http://tempuri.org/IInvoice/GetByIdBusinessLogicFaultFault", Name="BusinessLogicFault", Namespace="http://idu0080.ttu.ee")]
        OpenERP.Web.WCF.Invoice.AccountInvoice GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/GetById", ReplyAction="http://tempuri.org/IInvoice/GetByIdResponse")]
        System.Threading.Tasks.Task<OpenERP.Web.WCF.Invoice.AccountInvoice> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/GetByNumber", ReplyAction="http://tempuri.org/IInvoice/GetByNumberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OpenERP.Web.WCF.Invoice.BusinessLogicFault), Action="http://tempuri.org/IInvoice/GetByNumberBusinessLogicFaultFault", Name="BusinessLogicFault", Namespace="http://idu0080.ttu.ee")]
        OpenERP.Web.WCF.Invoice.AccountInvoice GetByNumber(string number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/GetByNumber", ReplyAction="http://tempuri.org/IInvoice/GetByNumberResponse")]
        System.Threading.Tasks.Task<OpenERP.Web.WCF.Invoice.AccountInvoice> GetByNumberAsync(string number);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInvoiceChannel : OpenERP.Web.WCF.Invoice.IInvoice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InvoiceClient : System.ServiceModel.ClientBase<OpenERP.Web.WCF.Invoice.IInvoice>, OpenERP.Web.WCF.Invoice.IInvoice {
        
        public InvoiceClient() {
        }
        
        public InvoiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InvoiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvoiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvoiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OpenERP.Web.WCF.Invoice.AccountInvoice Create(OpenERP.Web.WCF.Invoice.Customer customer, OpenERP.Web.WCF.Invoice.ProductProduct product, int quantity) {
            return base.Channel.Create(customer, product, quantity);
        }
        
        public System.Threading.Tasks.Task<OpenERP.Web.WCF.Invoice.AccountInvoice> CreateAsync(OpenERP.Web.WCF.Invoice.Customer customer, OpenERP.Web.WCF.Invoice.ProductProduct product, int quantity) {
            return base.Channel.CreateAsync(customer, product, quantity);
        }
        
        public OpenERP.Web.WCF.Invoice.AccountInvoice GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<OpenERP.Web.WCF.Invoice.AccountInvoice> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
        
        public OpenERP.Web.WCF.Invoice.AccountInvoice GetByNumber(string number) {
            return base.Channel.GetByNumber(number);
        }
        
        public System.Threading.Tasks.Task<OpenERP.Web.WCF.Invoice.AccountInvoice> GetByNumberAsync(string number) {
            return base.Channel.GetByNumberAsync(number);
        }
    }
}
