//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenERP.Web.WCF.Product {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OpenErpEntityBase", Namespace="http://schemas.datacontract.org/2004/07/OpenERP.Library")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OpenERP.Web.WCF.Product.ProductProduct))]
    public partial class OpenErpEntityBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductProduct", Namespace="http://schemas.datacontract.org/2004/07/OpenERP.Library")]
    [System.SerializableAttribute()]
    public partial class ProductProduct : OpenERP.Web.WCF.Product.OpenErpEntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DefaultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ean13Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HrExpenseOkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> IncomingQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> LstPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameTemplateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> OutgoingQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartnerRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PriceExtraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PriceMarginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PricelistIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductTmplIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProjectIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> QtyAvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TrackIncomingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TrackOutgoingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TrackProductionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValuationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VariantsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> VirtualAvailableField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultCode {
            get {
                return this.DefaultCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultCodeField, value) != true)) {
                    this.DefaultCodeField = value;
                    this.RaisePropertyChanged("DefaultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ean13 {
            get {
                return this.Ean13Field;
            }
            set {
                if ((object.ReferenceEquals(this.Ean13Field, value) != true)) {
                    this.Ean13Field = value;
                    this.RaisePropertyChanged("Ean13");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HrExpenseOk {
            get {
                return this.HrExpenseOkField;
            }
            set {
                if ((this.HrExpenseOkField.Equals(value) != true)) {
                    this.HrExpenseOkField = value;
                    this.RaisePropertyChanged("HrExpenseOk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> IncomingQty {
            get {
                return this.IncomingQtyField;
            }
            set {
                if ((this.IncomingQtyField.Equals(value) != true)) {
                    this.IncomingQtyField = value;
                    this.RaisePropertyChanged("IncomingQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LocationId {
            get {
                return this.LocationIdField;
            }
            set {
                if ((this.LocationIdField.Equals(value) != true)) {
                    this.LocationIdField = value;
                    this.RaisePropertyChanged("LocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> LstPrice {
            get {
                return this.LstPriceField;
            }
            set {
                if ((this.LstPriceField.Equals(value) != true)) {
                    this.LstPriceField = value;
                    this.RaisePropertyChanged("LstPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameTemplate {
            get {
                return this.NameTemplateField;
            }
            set {
                if ((object.ReferenceEquals(this.NameTemplateField, value) != true)) {
                    this.NameTemplateField = value;
                    this.RaisePropertyChanged("NameTemplate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> OutgoingQty {
            get {
                return this.OutgoingQtyField;
            }
            set {
                if ((this.OutgoingQtyField.Equals(value) != true)) {
                    this.OutgoingQtyField = value;
                    this.RaisePropertyChanged("OutgoingQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartnerRef {
            get {
                return this.PartnerRefField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerRefField, value) != true)) {
                    this.PartnerRefField = value;
                    this.RaisePropertyChanged("PartnerRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> PriceExtra {
            get {
                return this.PriceExtraField;
            }
            set {
                if ((this.PriceExtraField.Equals(value) != true)) {
                    this.PriceExtraField = value;
                    this.RaisePropertyChanged("PriceExtra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> PriceMargin {
            get {
                return this.PriceMarginField;
            }
            set {
                if ((this.PriceMarginField.Equals(value) != true)) {
                    this.PriceMarginField = value;
                    this.RaisePropertyChanged("PriceMargin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PricelistId {
            get {
                return this.PricelistIdField;
            }
            set {
                if ((this.PricelistIdField.Equals(value) != true)) {
                    this.PricelistIdField = value;
                    this.RaisePropertyChanged("PricelistId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductTmplId {
            get {
                return this.ProductTmplIdField;
            }
            set {
                if ((this.ProductTmplIdField.Equals(value) != true)) {
                    this.ProductTmplIdField = value;
                    this.RaisePropertyChanged("ProductTmplId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProjectId {
            get {
                return this.ProjectIdField;
            }
            set {
                if ((this.ProjectIdField.Equals(value) != true)) {
                    this.ProjectIdField = value;
                    this.RaisePropertyChanged("ProjectId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> QtyAvailable {
            get {
                return this.QtyAvailableField;
            }
            set {
                if ((this.QtyAvailableField.Equals(value) != true)) {
                    this.QtyAvailableField = value;
                    this.RaisePropertyChanged("QtyAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TrackIncoming {
            get {
                return this.TrackIncomingField;
            }
            set {
                if ((this.TrackIncomingField.Equals(value) != true)) {
                    this.TrackIncomingField = value;
                    this.RaisePropertyChanged("TrackIncoming");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TrackOutgoing {
            get {
                return this.TrackOutgoingField;
            }
            set {
                if ((this.TrackOutgoingField.Equals(value) != true)) {
                    this.TrackOutgoingField = value;
                    this.RaisePropertyChanged("TrackOutgoing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TrackProduction {
            get {
                return this.TrackProductionField;
            }
            set {
                if ((this.TrackProductionField.Equals(value) != true)) {
                    this.TrackProductionField = value;
                    this.RaisePropertyChanged("TrackProduction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valuation {
            get {
                return this.ValuationField;
            }
            set {
                if ((object.ReferenceEquals(this.ValuationField, value) != true)) {
                    this.ValuationField = value;
                    this.RaisePropertyChanged("Valuation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Variants {
            get {
                return this.VariantsField;
            }
            set {
                if ((object.ReferenceEquals(this.VariantsField, value) != true)) {
                    this.VariantsField = value;
                    this.RaisePropertyChanged("Variants");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> VirtualAvailable {
            get {
                return this.VirtualAvailableField;
            }
            set {
                if ((this.VirtualAvailableField.Equals(value) != true)) {
                    this.VirtualAvailableField = value;
                    this.RaisePropertyChanged("VirtualAvailable");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessLogicFault", Namespace="http://idu0080.ttu.ee")]
    [System.SerializableAttribute()]
    public partial class BusinessLogicFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF.Product.IProduct")]
    public interface IProduct {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/SearchById", ReplyAction="http://tempuri.org/IProduct/SearchByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OpenERP.Web.WCF.Product.BusinessLogicFault), Action="http://tempuri.org/IProduct/SearchByIdBusinessLogicFaultFault", Name="BusinessLogicFault", Namespace="http://idu0080.ttu.ee")]
        OpenERP.Web.WCF.Product.ProductProduct SearchById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/SearchById", ReplyAction="http://tempuri.org/IProduct/SearchByIdResponse")]
        System.Threading.Tasks.Task<OpenERP.Web.WCF.Product.ProductProduct> SearchByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/SearchByName", ReplyAction="http://tempuri.org/IProduct/SearchByNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OpenERP.Web.WCF.Product.BusinessLogicFault), Action="http://tempuri.org/IProduct/SearchByNameBusinessLogicFaultFault", Name="BusinessLogicFault", Namespace="http://idu0080.ttu.ee")]
        OpenERP.Web.WCF.Product.ProductProduct[] SearchByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/SearchByName", ReplyAction="http://tempuri.org/IProduct/SearchByNameResponse")]
        System.Threading.Tasks.Task<OpenERP.Web.WCF.Product.ProductProduct[]> SearchByNameAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductChannel : OpenERP.Web.WCF.Product.IProduct, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductClient : System.ServiceModel.ClientBase<OpenERP.Web.WCF.Product.IProduct>, OpenERP.Web.WCF.Product.IProduct {
        
        public ProductClient() {
        }
        
        public ProductClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OpenERP.Web.WCF.Product.ProductProduct SearchById(int id) {
            return base.Channel.SearchById(id);
        }
        
        public System.Threading.Tasks.Task<OpenERP.Web.WCF.Product.ProductProduct> SearchByIdAsync(int id) {
            return base.Channel.SearchByIdAsync(id);
        }
        
        public OpenERP.Web.WCF.Product.ProductProduct[] SearchByName(string name) {
            return base.Channel.SearchByName(name);
        }
        
        public System.Threading.Tasks.Task<OpenERP.Web.WCF.Product.ProductProduct[]> SearchByNameAsync(string name) {
            return base.Channel.SearchByNameAsync(name);
        }
    }
}
